# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eca46a0c92b7810dbcc1aa167c5b3ec1d4a38824ed1f40b8ad349d67f9bfb72bca03e0517506b4519bf73cdb43b6c1d2b667b765f02b3ff3e8fa63378132891

test:
  secret_key_base: 5786c1c7c1d0e3d559570dbc3b36bac9b7e622d19b82173418898963ba37dd5a5a4a2ae83e627ff17b20c80188f59ba0d5b2c56b6204536f139a8ae7c938e644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
